### Access admin route to trigger emails
### the token payload is the current date for which to get alerts
POST http://localhost:4000/admin
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRlIjoiMjAyMS0wNi0wOCIsImlhdCI6MTYyMzE2Mjg2MiwiZXhwIjoxNjIzMTY2NDYyfQ.-O454mCpBIqcKIlLaU8GeZdX_H_TLJolfSLEKR5mrnM